### ISSUE TITLE
Draft outline for lectures

### ISSUE THREAD

**Issue by cgranade** [QuinnPhys/PythonWorkshop-science#3]
Following the lively discussion in #1, I'm creating a new issue to split off discussion of the content of the lectures from logistical planning. I think it's worth continuing to talk about what we should and should not cover, but I want to keep that separate from figuring out things like room bookings and catering. Thanks for your help!

**Comment by cgranade** [comment]
@Travis-S said (#1):

> Workshops based on material from the Software Carpentry foundation often have pre-installation instructions for the command line, git, and Python. See here for a list of such workshops. Maybe sending out some of that material beforehand, with a "in case you wanted to try this on your own" disclaimer, could be useful?
> 
> 👍 for this workshop! Some of us at CQuIC are looking to do something similar, and would love to hear how your experience goes.

Thanks for the kind words! Duly noted about Software Carpentry, and I think that's a good point to raise. That said, we're aiming for something a little bit different in this workshop than what SC normally does. In particular, I would posit that many (but not all) physicists have had very little to no opportunity to learn computational skills in their undergraduate careers, meaning that they've had to figure a lot out on their own. There's many physicists for whom following a list of install instructions would be daunting at best and useless at the worst; in either case, we would lose them as students, which would be a missed opportunity to be of service. To address that, I think we need to be on hand to help with _any_ installation problems.

Moreover, I'd like to focus on more maintainable ways of installing software by focusing on package management where applicable (sorry, OS X and macOS users; I don't want to cover Homebrew or similar given the time constraints). With Chocolatey, Windows now has something almost as easy to use as `apt-get`, which means that with a quick tutorial, we can save a lot of pain for installing (for instance) the MS-official port of OpenSSH and an HTTPS-delivered version of PuTTY (this is only approximately true, see below).

If after this, we decide to host a second workshop, I think that puts us in a much better place to recommend pre-workshop installations, as we'd already have working tried and true lecture notes as well as participants from this run of things. At that point, we could list `choco`/`apt-get` and `conda`/`pip` invocations to get up and running and focus tutorials on more subtle install procedures.

---

**NB:** PuTTY is not actually installed using HTTPS by running `choco install putty`, but the hash of the insecurely-delivered file is verified against an HTTPS-delivered list of checksums, so it's at least better off. I think the compromise of trusting Chocolatey's hash of the insecurely-delivered installer is probably a reasonable one, but I'm happy to discuss further.

I'd be happy to leave PuTTY behind entirely, but we kind of need Pageant to offer an SSH agent, as the MS port of OpenSSH doesn't offer an agent that works "nicely" with Windows-style workflows, being a literal port to the Win32 crypto API. I don't relish the idea of getting robust and understandable instructions for getting the OpenSSH agent working well with modern text editors on Windows.

**Comment by cgranade** [comment]
Some outstanding issues I'd like to address with the outlines as they stand now:
- [x] **Drop "basic" and "intro."** These could come off as condescending. My point with suggesting "introductory" topics isn't to shame people for not knowing, but to offer opportunities typically not given in physics undergraduate and graduate education.
- [x] **Split Lecture 0.** Instead of one three-hour block with an awkward pause, the first lecture should probably be split into two orthogonal lectures.
- [ ] **Provide or link to LaTeX config instructions.** There's a few subtleties in getting LaTeX working, especially on Windows, with text editors, PDF readers and reference managers. While this is strictly out of scope, if we introduce Sublime Text and VS Code as tools without at least linking to instructions on how to use them w/ LaTeX, we'll wind up just creating more frustrations for attendees. (Note to self on this: SumatraPDF needs to be pointed at sublime text before reverse search works.)

**Comment by crazy4pi314** [comment]
>  Drop "basic" and "intro." 

Agree wholeheartedly.

>  Split Lecture 0. 

yeah after the ssh stuff seems natural

> Provide or link to LaTeX config instructions. 

Yup, prolly some good online resources for that already, Ill look for them.

**Comment by cgranade** [comment]
Since we more or less have the outlines in place and have moved on to actually getting a lot of the writing done, I'm going to close this issue and create one more focused on the content.
